export enum ChatType {
  PRIVATE = 'PRIVATE',
  GROUP = 'GROUP',
  CHANNEL = 'CHANNEL',
  COMMUNITY = 'COMMUNITY',
}

export enum ChatRole {
  OWNER = 'OWNER',
  ADMIN = 'ADMIN',
  MODERATOR = 'MODERATOR',
  MEMBER = 'MEMBER',
  SUBSCRIBER = 'SUBSCRIBER',
}

export enum MessageType {
  SYSTEM = 'SYSTEM',
  TEXT = 'TEXT',
  IMAGE = 'IMAGE',
  VIDEO = 'VIDEO',
  AUDIO = 'AUDIO',
  FILE = 'FILE',
  DOCUMENT = 'DOCUMENT',
  STICKER = 'STICKER',
  VOICE = 'VOICE',
  VIDEO_NOTE = 'VIDEO_NOTE',
  LOCATION = 'LOCATION',
  CONTACT = 'CONTACT',
  POLL = 'POLL',
  DICE = 'DICE',
  GAME = 'GAME',
  EMOJI = 'EMOJI',
  GIF = 'GIF',
  MARKDOWN = 'MARKDOWN',
  CUSTOM_EMOJI = 'CUSTOM_EMOJI',
  STICKER_PACK = 'STICKER_PACK',
}

export enum ChatPermission {
  SEND_MESSAGES = 'SEND_MESSAGES',
  SEND_MEDIA = 'SEND_MEDIA',
  ADD_MEMBERS = 'ADD_MEMBERS',
  REMOVE_MEMBERS = 'REMOVE_MEMBERS',
  EDIT_INFO = 'EDIT_INFO',
  PIN_MESSAGES = 'PIN_MESSAGES',
  DELETE_MESSAGES = 'DELETE_MESSAGES',
  BAN_MEMBERS = 'BAN_MEMBERS',
  MANAGE_PERMISSIONS = 'MANAGE_PERMISSIONS',
}
